// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOJ-QVndNRqtI8Go3uusNZb9QCZeH5ELA',
    appId: '1:612970784444:web:cf22dd6cdfccd319ad52b9',
    messagingSenderId: '612970784444',
    projectId: 'grocery-shopping-app-e53b4',
    authDomain: 'grocery-shopping-app-e53b4.firebaseapp.com',
    storageBucket: 'grocery-shopping-app-e53b4.firebasestorage.app',
    measurementId: 'G-XJG6KQ20ZN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEojkoRFlceV2Lv5nMQzS9KeLlp51Jx0I',
    appId: '1:612970784444:android:19dd0314494865b3ad52b9',
    messagingSenderId: '612970784444',
    projectId: 'grocery-shopping-app-e53b4',
    storageBucket: 'grocery-shopping-app-e53b4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEZYBcSqR2zPEYIFMdOl-lCWSXKL5bspk',
    appId: '1:612970784444:ios:9682bc28b29a01d5ad52b9',
    messagingSenderId: '612970784444',
    projectId: 'grocery-shopping-app-e53b4',
    storageBucket: 'grocery-shopping-app-e53b4.firebasestorage.app',
    iosBundleId: 'com.example.appCode',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEZYBcSqR2zPEYIFMdOl-lCWSXKL5bspk',
    appId: '1:612970784444:ios:9682bc28b29a01d5ad52b9',
    messagingSenderId: '612970784444',
    projectId: 'grocery-shopping-app-e53b4',
    storageBucket: 'grocery-shopping-app-e53b4.firebasestorage.app',
    iosBundleId: 'com.example.appCode',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOJ-QVndNRqtI8Go3uusNZb9QCZeH5ELA',
    appId: '1:612970784444:web:1d274648ea8fb17ead52b9',
    messagingSenderId: '612970784444',
    projectId: 'grocery-shopping-app-e53b4',
    authDomain: 'grocery-shopping-app-e53b4.firebaseapp.com',
    storageBucket: 'grocery-shopping-app-e53b4.firebasestorage.app',
    measurementId: 'G-Z5T3XFQFL5',
  );
}
