// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-nURrYeVlmPB2KPcp2RuSRlOn8PbQyls',
    appId: '1:1085697654596:android:607364c7ada574cf6b2111',
    messagingSenderId: '1085697654596',
    projectId: 'dima-2026',
    storageBucket: 'dima-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBQ9oR3PBm1-9XofEHvUBP5_8-Voao1lU',
    appId: '1:1085697654596:ios:e0b5aa9f8a2ad8596b2111',
    messagingSenderId: '1085697654596',
    projectId: 'dima-2026',
    storageBucket: 'dima-2026.firebasestorage.app',
    iosBundleId: 'com.example.appCode',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBn5GfIsy7STNEEcYqMndTtq9x-AM6oaok',
    appId: '1:1085697654596:web:fe488d42a4f1e0956b2111',
    messagingSenderId: '1085697654596',
    projectId: 'dima-2026',
    authDomain: 'dima-2026.firebaseapp.com',
    storageBucket: 'dima-2026.firebasestorage.app',
    measurementId: 'G-Q7WRQJBJGQ',
  );

}